In [2]:
import numpy as np

In [5]:
#simple 1-D array

a = np.array([1,2,3])
b = np.array([3,4,5])

print(a*b)

array([ 3,  8, 15])

In [10]:
#3-D array

c = np.array([[[1.0,2.0,3.0], [4.0,5.0,6.0]],[[6.0,7.0,8.0],[9.0,10.0,11.0]]])
print(c)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [11]:
#To get the dimension of array

a.ndim
c.ndim

3

In [12]:
#To get the shape of array

c.shape

(2, 2, 3)

In [14]:
#To get the data type

c.dtype

dtype('float64')

In [20]:
#To change the data type

d = np.array([1,2,3,4,5], dtype='int8')
print(d)

d.dtype

[1 2 3 4 5]


dtype('int8')

In [21]:
# Get Size for int8 - 1 byte, int16 - 2 byte and so on

a.itemsize
d.itemsize

1

In [22]:
#Total size = d.size * d.itemsize

d.nbytes

5

**Accessing/Changing specific elements, rows, columns etc.**

In [23]:
e = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(e)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
#Get a specific element [r,c]

e[1,3]

11

In [25]:
#Get a specific row

e[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [26]:
#Get specific column 

e[:, 4]

array([ 5, 12])

In [27]:
# [startindex:endindex:stepsize]

e[1, 0:6:2]

array([ 8, 10, 12])

In [35]:
#changing an element in the array

e[1:] = [8,9,10,11,12,13,14]

print(e)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [36]:
#3-D Array

f = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [37]:
#Get specific element (work outside in)

f[1,0,1]

8

**Initializing Different Types of Arrays**

In [40]:
#All zeros

np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [42]:
# All One's matrix

np.ones((3,3,3), dtype= 'int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [43]:
# Any other number (shape, number)

np.full((3,3), 69)

array([[69, 69, 69],
       [69, 69, 69],
       [69, 69, 69]])

In [48]:
# Any other number (full_like)

np.full_like(f, 5)

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

In [51]:
# random decimal number

np.random.rand(4,2)

np.random.random_sample(c.shape)

array([[[0.49064051, 0.20432617, 0.55348178],
        [0.2520387 , 0.18405709, 0.90503125]],

       [[0.80450462, 0.87445636, 0.53839473],
        [0.67843417, 0.44380581, 0.98381743]]])

In [54]:
# Random int value (value eg. 4,7,    size(3,4))

np.random.randint(f)

array([[[0, 1, 0],
        [2, 1, 5]],

       [[5, 7, 6],
        [6, 2, 8]]])

In [55]:
#Identity matrix

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
#Repeat Arrays

arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [78]:
output = np.ones((5,5))
output[1:4, 1:4] = 0
output[2,2] = 9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Make a copy**

In [82]:
g = ([1,2,3,4])
h = g.copy()
h[3] = 20
g

[1, 2, 3, 4]

**Mathematics

In [3]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])

#    a+b     a+2

#    a-b     a-2

#   a*b     a*2
    
#   a/b     a/2

a**b



array([    1,    32,   729, 16384], dtype=int32)

In [4]:
# Take a sin, cos, tan

np.sin(a) 

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

**Linear Algebra**

In [6]:
#Multiply matrices

a = np.ones((2,3))
b = np.full((3,2), 2)

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [9]:
#Find the determinant

c = np.identity(3)
np.linalg.det(c)

1.0

 https://github.com/KeithGalli/NumPy

**Statistics**

In [11]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.min(stats,axis=1)

array([1, 4])

In [13]:
np.max(stats, axis=1)

array([3, 6])

In [16]:
np.sum(stats, 0)

21

**Reorganising arrays**

In [21]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [23]:
#Vertically stacking Vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
#Horizontal stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

**Loading Data from file**

In [26]:
filedata = np.genfromtxt('data.txt', delimiter= ",")
filedata = filedata.astype('int32')
filedata

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

**Boolean Masking and Advanced indexing**

In [33]:
filedata > 50

filedata[filedata > 23]

np.any(filedata > 5, axis=0)

np.all(filedata > 5, axis=0)

# ~ means not

(~((filedata > 5) & (filedata < 10)))

array([[ True,  True,  True,  True,  True, False, False, False, False,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

**Thank your for viewing this project till the end.**

**Follow me on LinkedIn** >   https://www.linkedin.com/shubhamrastogi98

**Follow me on Github**   >   https://www.github.com/wokeshubham